server:
  port: 8080

spring:
  application:
    name: pagamento-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/erfood-pagamento?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: E@300303

  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: update

